// 3D Comic Keycap Portfolio Console Configuration
// Master Prompt — 3D Comic Keycap Portfolio Summary Box
// Colors and styling benchmarked directly against reference image (media_1791394588456.jpg)

export const CONSOLE_PALETTE = {
  comicBlack: "#171717",
  caseDark: "#242426",
  caseMid: "#323236",
  keyCream: "#F2EEE4",
  mechGray: "#858585",
  mechGrayDark: "#4a4a4e",
  comicRed: "#D93434",
  comicBlue: "#2867B2",
  comicYellow: "#E8A928",
  comicGreen: "#4C8A4A",
  comicOrange: "#E66B2D",
};

export const CONSOLE_KEYS = [
  // --- TOP ROW (P - O - R - T - F) ---
  {
    id: "key-p",
    char: "P",
    sublabel: "PROJECTS",
    title: "Selected Work",
    tagline: "High-impact AI, Machine Learning & Data pipelines.",
    terminalHoverText: "> OPENING SELECTED WORK & AI PIPELINES...",
    shortcut: "p",
    color: CONSOLE_PALETTE.keyCream,
    baseColor: CONSOLE_PALETTE.mechGray,
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "white",
    sectionId: "projects",
    modalType: "projects",
    staggerIndex: 0,
  },
  {
    id: "key-o1",
    char: "O",
    sublabel: "ABOUT",
    title: "About Moazzem",
    tagline: "Curious mind building digital experiences & intelligent data products.",
    terminalHoverText: "> LOADING ABOUT MOAZZEM...",
    shortcut: "o",
    color: CONSOLE_PALETTE.keyCream,
    baseColor: CONSOLE_PALETTE.mechGray,
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "white",
    sectionId: "about",
    modalType: "about",
    staggerIndex: 1,
  },
  {
    id: "key-r",
    char: "R",
    sublabel: "PROCESS",
    title: "Tech Stack & Process",
    tagline: "From hypothesis and clean data ingestion to model training and deployment.",
    terminalHoverText: "> ACCESSING TECH STACK & METHODOLOGY...",
    shortcut: "r",
    color: CONSOLE_PALETTE.comicBlue, // Reference: Enter / Control blue
    baseColor: "#17447d",
    textColor: "#FFFFFF",
    accentType: "blue",
    sectionId: "skills",
    modalType: "skills",
    staggerIndex: 2,
  },
  {
    id: "key-t",
    char: "T",
    sublabel: "WHAT I DO",
    title: "Services & Skills",
    tagline: "Machine Learning, LLM Agents, Data Analytics & Full-Stack Dashboards.",
    terminalHoverText: "> EXPLORING SERVICES & SKILLS...",
    shortcut: "t",
    color: CONSOLE_PALETTE.comicYellow, // Reference: Yellow arrow accent
    baseColor: "#9c6d12",
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "yellow",
    sectionId: "skills",
    modalType: "services",
    staggerIndex: 3,
  },
  {
    id: "key-f",
    char: "F",
    sublabel: "EXPLORE",
    title: "Explore Repositories",
    tagline: "Live GitHub code, open-source repos, stars, and commits.",
    terminalHoverText: "> CONNECTING TO GITHUB REPOSITORIES...",
    shortcut: "f",
    color: CONSOLE_PALETTE.comicRed, // Reference: Backspace / Shift red
    baseColor: "#8f1e1e",
    textColor: "#FFFFFF",
    accentType: "red",
    sectionId: "repositories",
    modalType: "repositories",
    staggerIndex: 4,
  },

  // --- LOWER ROW (O - L - I - O - ★ - LET'S TALK ↵) ---
  {
    id: "key-o2",
    char: "O",
    sublabel: "BIO",
    title: "Education & Bio",
    tagline: "BRAC University, CS Degree, Golden A+ Scholarship & Background.",
    terminalHoverText: "> ACCESSING EDUCATION & BACKGROUND...",
    shortcut: "b",
    color: CONSOLE_PALETTE.keyCream,
    baseColor: CONSOLE_PALETTE.mechGray,
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "white",
    sectionId: "education",
    modalType: "education",
    staggerIndex: 5,
  },
  {
    id: "key-l",
    char: "L",
    sublabel: "RESEARCH",
    title: "Deep Research",
    tagline: "DeepSenseV2V 60 GHz Beam Prediction & Telecom Churn Literature Audit.",
    terminalHoverText: "> RETRIEVING DEEP RESEARCH & PAPERS...",
    shortcut: "l",
    color: CONSOLE_PALETTE.comicBlack, // Reference: Dark F-row caps
    baseColor: "#0a0a0c",
    textColor: "#FFFFFF",
    accentType: "dark",
    sectionId: "projects",
    modalType: "research",
    staggerIndex: 6,
  },
  {
    id: "key-i",
    char: "I",
    sublabel: "AGENTS",
    title: "AI Agents & RAG",
    tagline: "LangChain & LangGraph autonomous agents, tools and vector embeddings.",
    terminalHoverText: "> INITIALIZING AGENTS & RAG TOOLS...",
    shortcut: "i",
    color: CONSOLE_PALETTE.keyCream,
    baseColor: CONSOLE_PALETTE.mechGray,
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "white",
    sectionId: "projects",
    modalType: "agents",
    staggerIndex: 7,
  },
  {
    id: "key-o3",
    char: "O",
    sublabel: "HELLO",
    title: "Say Hello",
    tagline: "Have a project or opportunity? Email me directly or connect on LinkedIn.",
    terminalHoverText: "> PREPARING DIRECT COMMUNICATION...",
    shortcut: "h",
    color: CONSOLE_PALETTE.comicYellow,
    baseColor: "#9c6d12",
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "yellow",
    sectionId: "contact",
    modalType: "contact",
    staggerIndex: 8,
  },
  {
    id: "key-star",
    char: "★",
    sublabel: "PORTFOLIO",
    title: "Explore My Portfolio",
    tagline: "The complete interactive console map, stats, and verified credentials.",
    terminalHoverText: "> OPENING COMPLETE PORTFOLIO MAP...",
    shortcut: "s",
    color: CONSOLE_PALETTE.comicRed,
    baseColor: "#8f1e1e",
    textColor: "#FFFFFF",
    accentType: "red",
    sectionId: "projects",
    modalType: "hub",
    staggerIndex: 9,
  },
  {
    id: "key-talk",
    char: "LET'S TALK ↵",
    sublabel: "CONTACT",
    title: "Let's Talk",
    tagline: "moazzemhossain1510@gmail.com — Let's build something remarkable together.",
    terminalHoverText: "> ESTABLISHING DIRECT CONNECTION...",
    shortcut: "Enter",
    color: CONSOLE_PALETTE.keyCream,
    baseColor: CONSOLE_PALETTE.comicBlack,
    textColor: CONSOLE_PALETTE.comicBlack,
    accentType: "spacebar",
    isWide: true,
    isSpacebar: true,
    sectionId: "contact",
    modalType: "contact",
    staggerIndex: 10,
  },
];
